import React from "react";
import "../styles/index.scss";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Nav from "../component/homepage/Nav";
import NavBar from "./components/NavBar";
import BeerFooter from "../component/beers/beerFooter";
import Footer from "./components/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const RootLayout = ({ children }) => (
  <html lang="en">
    <body className="bg-black pt-16 md:pt-24 lg:pt-32 xl:max-w-[1500px] xl:mx-auto">
      <NavBar />
      <AntdRegistry>{children}</AntdRegistry>
      <Footer />
    </body>
  </html>
);

export default RootLayout;
